export function getLandingTheme(dark) {
    if (dark) {
        return {
            page: 'min-h-screen flex flex-col bg-slate-950 text-slate-100 font-sans selection:bg-indigo-600/40 selection:text-indigo-200 transition-colors duration-300',
            header: 'sticky top-0 z-50 w-full border-b border-slate-900 bg-slate-950/80 backdrop-blur-md relative',
            brand: 'text-sm font-black tracking-widest text-white group-hover:text-indigo-400 transition-colors uppercase',
            navLink: 'text-sm font-semibold text-slate-400 hover:text-indigo-400 transition-colors',
            mobileNavLink: 'pb-2 border-b border-slate-900 text-sm font-semibold text-slate-400 hover:text-indigo-400 transition-colors',
            mobileMenuOpen: 'md:hidden absolute top-full left-0 w-full overflow-hidden border-slate-900 bg-slate-950/95 backdrop-blur-lg transition-[max-height,opacity,transform,border-color] duration-300 ease-in-out',
            themeToggle: 'p-2 rounded-lg border border-slate-800 bg-slate-900/60 text-slate-300 hover:text-white hover:border-slate-700 transition-colors cursor-pointer',
            portalBtn: 'inline-flex items-center gap-1.5 py-2 px-4 rounded-xl text-xs font-bold bg-slate-900 border border-slate-800 text-slate-200 hover:bg-slate-800 hover:text-white hover:border-slate-700 transition-all shadow-sm',
            hamburger: 'md:hidden p-2 rounded-lg border border-slate-800 bg-slate-900/60 text-slate-300 hover:text-white transition-colors',
            section: 'border-t border-slate-900 bg-slate-950 relative overflow-hidden',
            sectionLabel: 'text-xs font-bold uppercase tracking-[0.25em] text-indigo-400',
            headingLg: 'text-3xl sm:text-4xl font-extrabold tracking-tight text-white leading-tight',
            headingXl: 'text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.1] text-white',
            subtext: 'text-slate-400 text-sm sm:text-base leading-relaxed',
            subtextSm: 'text-slate-400 text-sm leading-relaxed',
            body: 'text-xs sm:text-sm text-slate-300',
            statValue: 'text-xl sm:text-2xl font-black text-white',
            statLabel: 'text-xs font-semibold text-slate-500 uppercase tracking-wider',
            heroBadge: 'inline-flex items-center gap-2 px-3 py-1 rounded-full border border-indigo-500/20 bg-indigo-500/5 text-indigo-400 text-xs font-bold uppercase tracking-wider',
            heroTagline: 'text-base sm:text-lg text-slate-400 font-medium leading-relaxed max-w-xl mx-auto lg:mx-0',
            heroStatsBorder: 'grid grid-cols-2 sm:grid-cols-4 gap-4 pt-8 border-t border-slate-900',
            featureCard: 'group rounded-3xl border border-slate-900 bg-slate-900/30 p-6 space-y-4 hover:border-slate-800 hover:bg-slate-900/50 hover:shadow-xl transition-all duration-300',
            featureTitle: 'text-lg font-bold text-white transition-colors',
            featureBody: 'text-xs sm:text-sm leading-relaxed text-slate-400',
            formCard: 'rounded-3xl border border-slate-900 bg-slate-900/20 p-6 sm:p-8 backdrop-blur-md shadow-2xl relative',
            formLabel: 'text-xs font-bold text-slate-400 uppercase tracking-wide',
            formInput: 'p-3 text-xs sm:text-sm border border-slate-800 rounded-xl bg-slate-950/60 text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-colors w-full',
            orderDivider: 'space-y-4 pt-4 border-t border-slate-900 text-left',
            checkIcon: 'flex items-center justify-center w-5 h-5 rounded-full bg-indigo-500/10 text-indigo-400 shrink-0 mt-0.5',
            contactCard: 'group relative flex flex-col justify-between rounded-2xl border border-slate-800/80 bg-slate-900/30 backdrop-blur-sm p-5 sm:p-6 overflow-hidden transition-all duration-300 hover:border-slate-700/90 hover:bg-slate-900/55 hover:shadow-lg hover:shadow-indigo-950/20',
            contactLabel: 'text-[10px] font-bold uppercase tracking-[0.15em] text-slate-500',
            contactValue: 'text-sm sm:text-base font-semibold text-white mt-1.5 break-words leading-snug',
            contactDivider: 'relative pt-4 mt-5 border-t border-slate-800/80 flex items-center justify-between gap-2',
            trustPill: 'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-slate-800 bg-slate-900/50 text-[11px] font-semibold text-slate-400',
            contactFootnote: 'mt-5 text-center lg:text-left text-[11px] text-slate-600 font-medium',
            contactEmpty: 'rounded-2xl border border-dashed border-slate-800 bg-slate-900/20 p-10 text-center',
            contactGridBg: 'absolute inset-0 bg-[linear-gradient(to_right,#6366f108_1px,transparent_1px),linear-gradient(to_bottom,#6366f108_1px,transparent_1px)] bg-[size:56px_56px] [mask-image:radial-gradient(ellipse_80%_60%_at_50%_50%,#000_20%,transparent_100%)] pointer-events-none',
            footerDark: true,
        };
    }

    return {
        page: 'min-h-screen flex flex-col bg-[#f4f7fb] text-slate-800 font-sans selection:bg-indigo-200/60 selection:text-indigo-900 transition-colors duration-300',
        header: 'sticky top-0 z-50 w-full border-b border-slate-200/90 bg-white/90 backdrop-blur-md relative shadow-sm shadow-slate-200/40',
        brand: 'text-sm font-black tracking-widest text-slate-800 group-hover:text-indigo-600 transition-colors uppercase',
        navLink: 'text-sm font-semibold text-slate-600 hover:text-indigo-600 transition-colors',
        mobileNavLink: 'pb-2 border-b border-slate-200 text-sm font-semibold text-slate-600 hover:text-indigo-600 transition-colors',
        mobileMenuOpen: 'md:hidden absolute top-full left-0 w-full overflow-hidden border-slate-200 bg-white/95 backdrop-blur-lg transition-[max-height,opacity,transform,border-color] duration-300 ease-in-out shadow-lg shadow-slate-200/30',
        themeToggle: 'p-2 rounded-lg border border-slate-200 bg-slate-50 text-slate-600 hover:text-indigo-600 hover:border-indigo-200 transition-colors cursor-pointer',
        portalBtn: 'inline-flex items-center gap-1.5 py-2 px-4 rounded-xl text-xs font-bold bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 hover:text-indigo-700 hover:border-indigo-200 transition-all shadow-sm',
        hamburger: 'md:hidden p-2 rounded-lg border border-slate-200 bg-slate-50 text-slate-600 hover:text-indigo-600 transition-colors',
        section: 'border-t border-slate-200/90 bg-[#f4f7fb] relative overflow-hidden',
        sectionLabel: 'text-xs font-bold uppercase tracking-[0.25em] text-indigo-600',
        headingLg: 'text-3xl sm:text-4xl font-extrabold tracking-tight text-slate-900 leading-tight',
        headingXl: 'text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.1] text-slate-900',
        subtext: 'text-slate-600 text-sm sm:text-base leading-relaxed',
        subtextSm: 'text-slate-600 text-sm leading-relaxed',
        body: 'text-xs sm:text-sm text-slate-600',
        statValue: 'text-xl sm:text-2xl font-black text-slate-900',
        statLabel: 'text-xs font-semibold text-slate-500 uppercase tracking-wider',
        heroBadge: 'inline-flex items-center gap-2 px-3 py-1 rounded-full border border-indigo-200 bg-indigo-50 text-indigo-700 text-xs font-bold uppercase tracking-wider',
        heroTagline: 'text-base sm:text-lg text-slate-600 font-medium leading-relaxed max-w-xl mx-auto lg:mx-0',
        heroStatsBorder: 'grid grid-cols-2 sm:grid-cols-4 gap-4 pt-8 border-t border-slate-200',
        featureCard: 'group rounded-3xl border border-slate-200/90 bg-white p-6 space-y-4 hover:border-slate-300 hover:shadow-lg shadow-sm transition-all duration-300',
        featureTitle: 'text-lg font-bold text-slate-900 transition-colors',
        featureBody: 'text-xs sm:text-sm leading-relaxed text-slate-600',
        formCard: 'rounded-3xl border border-slate-200/90 bg-white p-6 sm:p-8 shadow-xl shadow-slate-200/50 relative',
        formLabel: 'text-xs font-bold text-slate-500 uppercase tracking-wide',
        formInput: 'p-3 text-xs sm:text-sm border border-slate-200 rounded-xl bg-slate-50 text-slate-800 placeholder-slate-400 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-colors w-full',
        orderDivider: 'space-y-4 pt-4 border-t border-slate-200 text-left',
        checkIcon: 'flex items-center justify-center w-5 h-5 rounded-full bg-indigo-50 text-indigo-600 shrink-0 mt-0.5',
        contactCard: 'group relative flex flex-col justify-between rounded-2xl border border-slate-200/90 bg-white backdrop-blur-sm p-5 sm:p-6 overflow-hidden transition-all duration-300 hover:border-slate-300 hover:shadow-md shadow-sm',
        contactLabel: 'text-[10px] font-bold uppercase tracking-[0.15em] text-slate-500',
        contactValue: 'text-sm sm:text-base font-semibold text-slate-800 mt-1.5 break-words leading-snug',
        contactDivider: 'relative pt-4 mt-5 border-t border-slate-100 flex items-center justify-between gap-2',
        trustPill: 'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-slate-200 bg-white text-[11px] font-semibold text-slate-600 shadow-sm',
        contactFootnote: 'mt-5 text-center lg:text-left text-[11px] text-slate-500 font-medium',
        contactEmpty: 'rounded-2xl border border-dashed border-slate-300 bg-white/80 p-10 text-center',
        contactGridBg: 'absolute inset-0 bg-[linear-gradient(to_right,#94a3b818_1px,transparent_1px),linear-gradient(to_bottom,#94a3b818_1px,transparent_1px)] bg-[size:56px_56px] [mask-image:radial-gradient(ellipse_80%_60%_at_50%_50%,#000_20%,transparent_100%)] pointer-events-none',
        footerDark: false,
    };
}
